spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false
      database: ${mongo-db}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${user-name}
    password: ${password}
    destination-mail: ${destination-mail}
    from-mail: ${from-mail}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

